name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


env:
  IMAGE_NAME: liatrio-demo
  IMAGE_TAG: ci-${{ github.run_number }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run unit tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t "$IMAGE_NAME:$IMAGE_TAG" .

      - name: Start application container
        run: docker run -d --name liatrio-demo-ci -p 80:80 "$IMAGE_NAME:$IMAGE_TAG"

      - name: Wait for service
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1/ > /dev/null; then
              exit 0
            fi
            sleep 1
          done
          docker logs liatrio-demo-ci
          exit 1

      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master

      - name: Stop application container
        if: always()
        run: docker rm -f liatrio-demo-ci || true
